version: '2'
services:
  # The Application
  app:
    build:
      context: ./
      args:
        - WITH_XDEBUG=false
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - "PHP_IDE_CONFIG=serverName=docker"
    env_file:
      - .env

  # The Web Server
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
      args:
        - APP_ENV=develop
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 80:80
  database:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    env_file:
      - .env