version: '3.3'

services:
  web:
    image: pablofmorales/apache-php7
    container_name: web
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./apache.conf:/etc/apache2/sites-enabled/myproject-web.conf
      - ./var/log:/var/log/apache2
    links:
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    env_file:
      - .env

